### ISSUE TITLE
Missing dependecies on structs

### ISSUE THREAD

**Issue by Darkratos** [cursey/ue4genny#6]
Hey, another problem I noticed is that the code doesn't handle TArray's (and probably other template types) dependencies.
I'm doing a fix here (in the generate_fproperty function), but this is also something to look at in a future update.

**Comment by cursey** [comment]
A real fix for this should be implemented in SdkGenny not in UE4Genny. I'll work on it soon. Thanks for reminding me about this.

**Comment by cursey** [comment]
I've implemented a fix for this in SdkGenny (d3407ec46365645b40fc5cde27303660298fc586). I've also updated this projects version of SdkGenny to the latest.

**Comment by Darkratos** [comment]
Alright, this fixed most of the issue, but functions that take a TArray as a parameter still need resolving.

**Comment by cursey** [comment]
> functions that take a TArray as a parameter still need resolving.

Can you give me an example of where this is failing? I've reviewed the relevant SdkGenny code and it should be handling function parameters that use generic types properly.

**Comment by Darkratos** [comment]
Sure:
class APlayerControler has this function:

`void ClientUpdateMultipleLevelsStreamingStatus(TArray<FUpdateLevelStreamingLevelStatus>& LevelStatuses);`

and FUpdateLevelStreamingLevelStatus isn't included.
Also, many enum which have scoped types throw an error on forward declarations.
And to top it off, the .cpp files need to also have a dependency on UClass, which is not included as well.

**Comment by cursey** [comment]
> `void ClientUpdateMultipleLevelsStreamingStatus(TArray<FUpdateLevelStreamingLevelStatus>& LevelStatuses);`

Ah, I see. Probably because the parameter is a reference. I can fix that soon. 

> Also, many enum which have scoped types throw an error on forward declarations.

Can you give an example?

**Comment by Darkratos** [comment]
All forward declared enums.
The fix is to add the scope on the forward declaration.
Sadly I can't give you an exact example right now but it's always an ': uint8_t' missing.

**Comment by cursey** [comment]
Enums being forward declared might be a regression actually (from when I improved the dependency system). There's no reason to not just `#include` them as far as I can tell.

**Comment by cursey** [comment]
I think I've fixed both issues in https://github.com/cursey/sdkgenny/commit/20442e0675e549b0ff48895c76a7d066702e0c4a. I've also updated UE4Genny with these changes.

**Comment by Darkratos** [comment]
Alright! I'm going to try it out now and I'll give you the feedback in a bit!

**Comment by Darkratos** [comment]
The project gets so large that it takes a long time to compile, but, as far as I've seen, the main problem is fixed.
The undefined UClass isn't quite fixed yet, but I should be abre to just call the '->depends' on the generate_procedure to fix it.
